### ISSUE TITLE
Permission to update swc_core

### ISSUE THREAD

**Issue by padmaia** [wooorm/mdxjs-rs#13]
Hey @wooorm, would you be open to granting @jridgewell, @kwonoj, and @sokra permission to approve and merge pull requests to update swc_core? We have to keep swc_core versions in sync across Next.js, Turbopack, and mdxjs-rs, so this would help our publishing velocity quite a bit.

**Comment by wooorm** [comment]
Done! ✅ But sokra isn’t on crates.io, so I can‘t give them access.
