### ISSUE TITLE
Exposing the interface to return the transformed swc AST?

### ISSUE THREAD

**Issue by XiNiHa** [wooorm/mdxjs-rs#30]
I'd like to transform MDX to swc AST to make the package I'm working on ([tagged-md](https://github.com/portone-io/tagged-md)) to support transforming the content to JSX. Are you open for exposing the interface?

**Comment by wooorm** [comment]
This project generates entire files: a whole program.
How do you plan on injecting that AST into another AST?
Please tell me more about your use case.

**Comment by XiNiHa** [comment]
While it currently transforms the markdown as a string of HTML (and already using markdown-rs for it) some of the users requested to support transforming the markdown into JSX, maybe like this:

```jsx
const Component = () => (
  <main>
    {md`
      # Hello
    `}
  </main>
)
```

I see that `mdx-rs` is focused on transforming MDX into JavaScript, including imports and inline JS. Actually that sounds a bit mismatched with my use case 🤔 Maybe I should just build my own mdast => swc AST transformer ;(

**Comment by XiNiHa** [comment]
Sounds pretty good, thanks for the advice! I'll close the issue then 👍
