### ISSUE TITLE
chore:  compile error due to markdown changed AST struct

### ISSUE THREAD

**Issue by stormslowly** [wooorm/mdxjs-rs#54]
branch main has compile errors

eg:

`BlockQuote` to `Blockquote`

and MdxJsxExpressionAttribute  type

**Comment by wooorm** [comment]
That seems unlikely? `markdown-rs` is alpha. So the breaking change should not be pulled in?

**Comment by wooorm** [comment]
That shouldn’t happen. When you clone, you should get 1.0.0-alpha.18: https://github.com/wooorm/mdxjs-rs/blob/d57c0cadbfe6b24057da1f6a7bdd7bcf1906eab8/Cargo.toml#L19

**Comment by stormslowly** [comment]
according to  https://doc.rust-lang.org/cargo/reference/resolver.html

`1.0.0-alpha.18` is equivalent to `^1.0.0-alpha.18`,  so `1.0.0-alpha.21` matches the semver constrai.

if you want lock to `1.0.0-alpha.18` the semver should be `=1.0.0-alpha.18`

and you cargo lock file is not versioned in git,  you can add it to git, so someone else cloned the repo will get the same version.

you can try cargo update or  remove the cargo lock, then cargo build again.

**Comment by wooorm** [comment]
Thank you!
